
--2.1 

SELECT OrdenesNumero, ClientesNombre, EmpleadosNombres
FROM EMPLEADOS EMP
JOIN ORDENES ORDEN ON ORDEN.EMPLEADOSCODIGO = EMP.EMPLEADOSCODIGO
JOIN CLIENTES CTE ON CTE.CLIENTESCODIGO = ORDEN.CLIENTESCODIGO
ORDER BY CTE.ClientesNombre, ORDEN.OrdenesNumero

--2.2
SELECT COUNT(ORDEN.OrdenesNumero),  EMP.EmpleadosNombres
FROM EMPLEADOS EMP
JOIN ORDENES ORDEN ON ORDEN.EMPLEADOSCODIGO = EMP.EMPLEADOSCODIGO
GROUP BY EMP.EmpleadosNombres

--2.3 
UPDATE ORDENES SET OrdenesMontoTotal = OrdenesMontoTotal +(0.01*OrdenesMontoTotal)
WHERE OrdenesNumero IN (
SELECT OrdenesNumero
FROM ORDENES ORDEN
JOIN CLIENTES CTE ON CTE.CLIENTESCODIGO = ORDEN.CLIENTESCODIGO
WHERE CTE.ClientesNombre = 'Juan Perez'
)


--2.4
SELECT COUNT(ORDEN.OrdenesNumero),  PRODUCTOSDESCRIPCION
FROM PRODUCTOS PROD
JOIN DETALLEORDENES DET ON DET.PRODUCTOSCODIGO = PROD.PRODUCTOSCODIGO
JOIN ORDENES ORDEN ON ORDEN.OrdenesNumero=DET.OrdenesNumero 
JOIN CLIENTES CTE ON CTE.CLIENTESCODIGO = ORDEN.CLIENTESCODIGO
JOIN EMPLEADOS EMP ON ORDEN.EMPLEADOSCODIGO = EMP.EMPLEADOSCODIGO
WHERE PRODUCTOSDESCRIPCION IN ('Leche','Harina','Huevo')
AND ORDENESFECHA BETWEEN TO_DATE('01/01/2020 00:00:00','dd/mm/yyyy HH24:MI:SS') AND TO_DATE('31/03/2020 23:59:59','dd/mm/yyyy HH24:MI:SS')
AND CTE.ClientesNombre IN('Juan Perez','Pedro Hernandez' )
AND EMP.EmpleadosCodigo IN ('A01')
GROUP BY PRODUCTOSDESCRIPCION





